name: Nightly Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Set Build Version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          npm --no-git-tag-version version $CURRENT_VERSION-nightly.${{ github.run_number }}

      - name: Build Application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            release/*.dmg
            release/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          assets: '*'
          fail-if-no-assets: false
          fail-if-no-release: false

      - name: Update Nightly Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f nightly
          git push -f origin nightly

      - name: Publish Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: "🐷 Bản thử nghiệm mới nhất (Nightly)"
          body: "Bản build tự động mới nhất từ nhánh `master`."
          prerelease: true
          files: artifacts/*
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
